version: '2'
services:

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php:
    build:
      context: ./php-fpm
      args:
        - INSTALL_NODEJS=${DOCKER_INSTALL_NODEJS}
        - INSTALL_ENVOY=${DOCKER_INSTALL_ENVOY}
    depends_on:
      - db
    volumes:
      - ../:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ~/.composer/auth.json:/var/www/.composer/auth.json
    tty: true

  nginx:
    build: ./nginx
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ../:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
