version: '2'
services:

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php:
    build: .
    depends_on:
      - db
    links:
      - db
    volumes:
      - ../:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:latest
    depends_on:
      - php
    links:
      - php
    ports:
      - 8080:80
    volumes:
      - ../:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf